In [123]:
# install pandas
! pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [124]:
# import pandas
import pandas as pd

In [125]:
pd.__version__ # check installed pandas version

'2.2.3'

In [126]:
# Create DataFrame
# using Dictionary of Listing
data = {
    "name" : ["jack","jannu","chiku","shanti","sahil"],
    "age"  : [9,21,22,20,18],
    "salary":[20000,21000,25000,20000,18000],

}

In [127]:
df = pd.DataFrame(data)
print(df)

     name  age  salary
0    jack    9   20000
1   jannu   21   21000
2   chiku   22   25000
3  shanti   20   20000
4   sahil   18   18000

In [128]:
print(type(data))

<class 'dict'>

In [129]:
df.head(2) # top row

    name  age  salary
0   jack    9   20000
1  jannu   21   21000

In [130]:
df.tail(2) # last rows

     name  age  salary
3  shanti   20   20000
4   sahil   18   18000

In [131]:
df.shape # returns a tuple containing the shape of the DataFrame - row & column

(5, 3)

In [132]:
df.columns # list of column name in a DataFrame

Index(['name', 'age', 'salary'], dtype='object')

In [133]:
#column rename
df.rename(columns={"name":"Name","age":"Age","salary":"Salary"},inplace=True) # rename column name/s

In [134]:
df

     Name  Age  Salary
0    jack    9   20000
1   jannu   21   21000
2   chiku   22   25000
3  shanti   20   20000
4   sahil   18   18000

In [135]:
df.info() # info method prints information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Salary  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [136]:
df.describe() # describe method generates descriptive statistics of DataFrame, only for numerical-value column

             Age        Salary
count   5.000000      5.000000
mean   18.000000  20800.000000
std     5.244044   2588.435821
min     9.000000  18000.000000
25%    18.000000  20000.000000
50%    20.000000  20000.000000
75%    21.000000  21000.000000
max    22.000000  25000.000000

In [12]:
# Save and Load Data from CSV
df.to_csv("test_data.csv",index = False) #export data frame

In [13]:
load_df = pd.read_csv("test_data.csv") # load file -  import DataFrame
load_df

     Name  Age  Salary
0    jack    9   20000
1   jannu   21   21000
2   chiku   22   25000
3  shanti   20   20000
4   sahil   18   18000

In [14]:
# Row & Column - Selection
df[["Name","Salary"]] # select single column

     Name  Salary
0    jack   20000
1   jannu   21000
2   chiku   25000
3  shanti   20000
4   sahil   18000

In [15]:
# Select Rows
df.loc[df.Name == "jannu"] # loc - index name based

    Name  Age  Salary
1  jannu   21   21000

In [16]:
df.loc[(df.Name == "jannu") & (df.Salary >= 50000) ]

Empty DataFrame
Columns: [Name, Age, Salary]
Index: []

In [17]:
# iloc - index value based
df.iloc[0]

Name       jack
Age           9
Salary    20000
Name: 0, dtype: object

In [18]:
# Select Rows || iloc - index-value based
# df.iloc[0]
df.iloc[0:2]

    Name  Age  Salary
0   jack    9   20000
1  jannu   21   21000

In [19]:
df

     Name  Age  Salary
0    jack    9   20000
1   jannu   21   21000
2   chiku   22   25000
3  shanti   20   20000
4   sahil   18   18000

In [20]:
df["Age"] > 15

0    False
1     True
2     True
3     True
4     True
Name: Age, dtype: bool

In [21]:
df_age_filter = df[df["Age"] >=18] # filter and store dataframe in a new variable

In [22]:
df_age_filter

     Name  Age  Salary
1   jannu   21   21000
2   chiku   22   25000
3  shanti   20   20000
4   sahil   18   18000

In [23]:
df[(df["Age"] >=18 ) & (df["Salary"]>=50000)] # multiple filter conditions

Empty DataFrame
Columns: [Name, Age, Salary]
Index: []

In [24]:
df.where(df["Age"] >= 18)

     Name   Age   Salary
0     NaN   NaN      NaN
1   jannu  21.0  21000.0
2   chiku  22.0  25000.0
3  shanti  20.0  20000.0
4   sahil  18.0  18000.0

In [25]:
df.where(df["Age"] >= 18, other = "Not Eligible") # where function replace values in a DataFrame based on a condition

           Name           Age        Salary
0  Not Eligible  Not Eligible  Not Eligible
1         jannu            21         21000
2         chiku            22         25000
3        shanti            20         20000
4         sahil            18         18000

In [26]:
# Row and Columns = Operations (Add , Update,Delete)

In [27]:
df

     Name  Age  Salary
0    jack    9   20000
1   jannu   21   21000
2   chiku   22   25000
3  shanti   20   20000
4   sahil   18   18000

In [28]:
# add new column
df["Team"] = ["CEO","HR","CTO","DA","CEO"]
df

     Name  Age  Salary Team
0    jack    9   20000  CEO
1   jannu   21   21000   HR
2   chiku   22   25000  CTO
3  shanti   20   20000   DA
4   sahil   18   18000  CEO

In [29]:
# Add nwe column using existing column/s
df["Bonus"] = df["Salary"] * 0.2
df

     Name  Age  Salary Team   Bonus
0    jack    9   20000  CEO  4000.0
1   jannu   21   21000   HR  4200.0
2   chiku   22   25000  CTO  5000.0
3  shanti   20   20000   DA  4000.0
4   sahil   18   18000  CEO  3600.0

In [30]:
# Add new row - at the end of DataFrame
df.loc[len(df)] = ["ABC",21,30000,"DA",2000]
df

     Name  Age  Salary Team   Bonus
0    jack    9   20000  CEO  4000.0
1   jannu   21   21000   HR  4200.0
2   chiku   22   25000  CTO  5000.0
3  shanti   20   20000   DA  4000.0
4   sahil   18   18000  CEO  3600.0
5     ABC   21   30000   DA  2000.0

In [31]:
len(df)

6

In [32]:
# update value - using index name
df.loc[0,"Salary"] = 30000
df

     Name  Age  Salary Team   Bonus
0    jack    9   30000  CEO  4000.0
1   jannu   21   21000   HR  4200.0
2   chiku   22   25000  CTO  5000.0
3  shanti   20   20000   DA  4000.0
4   sahil   18   18000  CEO  3600.0
5     ABC   21   30000   DA  2000.0

In [33]:
# update value - using column name
df.loc[df.Name == "jannu" , "Salary"] = 90000

In [34]:
# delect value - row and column values

In [35]:
df.drop(df[df.Name == "ABC"].index) # drop row, axis = 0

     Name  Age  Salary Team   Bonus
0    jack    9   30000  CEO  4000.0
1   jannu   21   90000   HR  4200.0
2   chiku   22   25000  CTO  5000.0
3  shanti   20   20000   DA  4000.0
4   sahil   18   18000  CEO  3600.0

In [36]:
df.drop("Bonus",axis=1)

     Name  Age  Salary Team
0    jack    9   30000  CEO
1   jannu   21   90000   HR
2   chiku   22   25000  CTO
3  shanti   20   20000   DA
4   sahil   18   18000  CEO
5     ABC   21   30000   DA

In [37]:
df

     Name  Age  Salary Team   Bonus
0    jack    9   30000  CEO  4000.0
1   jannu   21   90000   HR  4200.0
2   chiku   22   25000  CTO  5000.0
3  shanti   20   20000   DA  4000.0
4   sahil   18   18000  CEO  3600.0
5     ABC   21   30000   DA  2000.0

In [38]:
df.drop("Bonus",axis=1,inplace=True) # delete one column
# df.drope(["Bonus","Team"], axis = 1, inplace = True) # delet multiple columns

In [39]:
df

     Name  Age  Salary Team
0    jack    9   30000  CEO
1   jannu   21   90000   HR
2   chiku   22   25000  CTO
3  shanti   20   20000   DA
4   sahil   18   18000  CEO
5     ABC   21   30000   DA

In [40]:
# for multipul 
# df.drop(["Bonus","team"],axis=1) # delete multiple column

In [41]:
df

     Name  Age  Salary Team
0    jack    9   30000  CEO
1   jannu   21   90000   HR
2   chiku   22   25000  CTO
3  shanti   20   20000   DA
4   sahil   18   18000  CEO
5     ABC   21   30000   DA

In [42]:
# sort value - order values in dataframe by asc oe desc order
df.sort_values("Salary") # assending order, by default

     Name  Age  Salary Team
4   sahil   18   18000  CEO
3  shanti   20   20000   DA
2   chiku   22   25000  CTO
0    jack    9   30000  CEO
5     ABC   21   30000   DA
1   jannu   21   90000   HR

In [43]:
df.sort_values("Salary",ascending = False) # dor decending

     Name  Age  Salary Team
1   jannu   21   90000   HR
0    jack    9   30000  CEO
5     ABC   21   30000   DA
2   chiku   22   25000  CTO
3  shanti   20   20000   DA
4   sahil   18   18000  CEO

In [44]:
# working with date value

In [59]:
# create a data column of joining
df["DOJ"] = ["20-01-2007" , "19-03-2012","13-12-2019","02-02-2009","19-10-2006","22-11-2007"]
df

     Name  Age  Salary Team         Doj         DOJ
0    jack    9   30000  CEO  2024-01-01  20-01-2007
1   jannu   21   90000   HR  2005-03-12  19-03-2012
2   chiku   22   25000  CTO  2013-12-29  13-12-2019
3  shanti   20   20000   DA  2002-02-29  02-02-2009
4   sahil   18   18000  CEO  2019-10-19  19-10-2006
5     ABC   21   30000   DA  2022-11-01  22-11-2007

In [60]:
df["DOJ"].dtype # object - type value

dtype('O')

In [62]:
df["DOJ"] = pd.to_datetime(df["DOJ"],dayfirst=True) # change to data-time type

In [64]:
df["DOJ"].dtype # date-time type

dtype('<M8[ns]')

In [66]:
df1 = df

In [67]:
# creating a new column with incorrect date formate
df1["DOJ2"] = ["20-01-2007" , "19-03-2012","13-12-2019","02-02-2009","19-10-2006","22-11-2007"]
df1

     Name  Age  Salary Team         Doj        DOJ        DOJ2
0    jack    9   30000  CEO  2024-01-01 2007-01-20  20-01-2007
1   jannu   21   90000   HR  2005-03-12 2012-03-19  19-03-2012
2   chiku   22   25000  CTO  2013-12-29 2019-12-13  13-12-2019
3  shanti   20   20000   DA  2002-02-29 2009-02-02  02-02-2009
4   sahil   18   18000  CEO  2019-10-19 2006-10-19  19-10-2006
5     ABC   21   30000   DA  2022-11-01 2007-11-22  22-11-2007

In [69]:
df1["DOJ2"].dtype #object-type value

dtype('O')

In [73]:
df1["DOJ2"] = pd.to_datetime(df1['DOJ2'], format = "%d-%m-%y") # change to date-time type using date-formate

In [74]:
df["DOJ2"].dtype

dtype('<M8[ns]')

In [75]:
df

     Name  Age  Salary Team         Doj        DOJ       DOJ2
0    jack    9   30000  CEO  2024-01-01 2007-01-20 2007-01-20
1   jannu   21   90000   HR  2005-03-12 2012-03-19 2012-03-19
2   chiku   22   25000  CTO  2013-12-29 2019-12-13 2019-12-13
3  shanti   20   20000   DA  2002-02-29 2009-02-02 2009-02-02
4   sahil   18   18000  CEO  2019-10-19 2006-10-19 2006-10-19
5     ABC   21   30000   DA  2022-11-01 2007-11-22 2007-11-22

In [78]:
df = df.drop('DOJ2',axis=1)
df

     Name  Age  Salary Team         Doj        DOJ
0    jack    9   30000  CEO  2024-01-01 2007-01-20
1   jannu   21   90000   HR  2005-03-12 2012-03-19
2   chiku   22   25000  CTO  2013-12-29 2019-12-13
3  shanti   20   20000   DA  2002-02-29 2009-02-02
4   sahil   18   18000  CEO  2019-10-19 2006-10-19
5     ABC   21   30000   DA  2022-11-01 2007-11-22

In [80]:
df = df.drop('Doj',axis=1)
df

     Name  Age  Salary Team        DOJ
0    jack    9   30000  CEO 2007-01-20
1   jannu   21   90000   HR 2012-03-19
2   chiku   22   25000  CTO 2019-12-13
3  shanti   20   20000   DA 2009-02-02
4   sahil   18   18000  CEO 2006-10-19
5     ABC   21   30000   DA 2007-11-22

In [81]:
# extract year
df["DOJ"].dt.year

0    2007
1    2012
2    2019
3    2009
4    2006
5    2007
Name: DOJ, dtype: int32

In [82]:
df["DOJ"].dt.month  # extract month

0     1
1     3
2    12
3     2
4    10
5    11
Name: DOJ, dtype: int32

In [83]:
df["DOJ"].dt.day # extract day

0    20
1    19
2    13
3     2
4    19
5    22
Name: DOJ, dtype: int32

In [84]:
df["DOJ"].dt.day_name() # extract day name

0    Saturday
1      Monday
2      Friday
3      Monday
4    Thursday
5    Thursday
Name: DOJ, dtype: object

In [85]:
# create new column using month extract function from DOJ column
df["Month"] = df["DOJ"].dt.month
df

     Name  Age  Salary Team        DOJ  Month
0    jack    9   30000  CEO 2007-01-20      1
1   jannu   21   90000   HR 2012-03-19      3
2   chiku   22   25000  CTO 2019-12-13     12
3  shanti   20   20000   DA 2009-02-02      2
4   sahil   18   18000  CEO 2006-10-19     10
5     ABC   21   30000   DA 2007-11-22     11

In [87]:
df["DOJ"] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2007-04-20
1   2012-06-17
2   2020-03-12
3   2009-05-03
4   2007-01-17
5   2008-02-20
Name: DOJ, dtype: datetime64[ns]

In [88]:
df

     Name  Age  Salary Team        DOJ  Month
0    jack    9   30000  CEO 2007-01-20      1
1   jannu   21   90000   HR 2012-03-19      3
2   chiku   22   25000  CTO 2019-12-13     12
3  shanti   20   20000   DA 2009-02-02      2
4   sahil   18   18000  CEO 2006-10-19     10
5     ABC   21   30000   DA 2007-11-22     11

In [89]:
# handaling missing values
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False
4  False  False   False  False  False  False
5  False  False   False  False  False  False

In [91]:
import numpy as np
df.loc[df.Name=="jack","Salary"] = np.nan

In [92]:
df

     Name  Age   Salary Team        DOJ  Month
0    jack    9      NaN  CEO 2007-01-20      1
1   jannu   21  90000.0   HR 2012-03-19      3
2   chiku   22  25000.0  CTO 2019-12-13     12
3  shanti   20  20000.0   DA 2009-02-02      2
4   sahil   18  18000.0  CEO 2006-10-19     10
5     ABC   21  30000.0   DA 2007-11-22     11

In [93]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False    True  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False
4  False  False   False  False  False  False
5  False  False   False  False  False  False

In [95]:
df.isnull().sum() # count of null values by columns

Name      0
Age       0
Salary    1
Team      0
DOJ       0
Month     0
dtype: int64

In [96]:
df.fillna(0) # fill null values with 0

     Name  Age   Salary Team        DOJ  Month
0    jack    9      0.0  CEO 2007-01-20      1
1   jannu   21  90000.0   HR 2012-03-19      3
2   chiku   22  25000.0  CTO 2019-12-13     12
3  shanti   20  20000.0   DA 2009-02-02      2
4   sahil   18  18000.0  CEO 2006-10-19     10
5     ABC   21  30000.0   DA 2007-11-22     11

In [98]:
# Aggregation and group by

In [100]:
df["Team"].value_counts()

Team
CEO    2
DA     2
HR     1
CTO    1
Name: count, dtype: int64

In [101]:
df["Month"].value_counts() # freaquency of value in month column

Month
1     1
3     1
12    1
2     1
10    1
11    1
Name: count, dtype: int64

In [102]:
df[df["Team"]=="CEO"].value_counts() # frequency of values in month column where month = 1

Name   Age  Salary   Team  DOJ         Month
sahil  18   18000.0  CEO   2006-10-19  10       1
Name: count, dtype: int64

In [104]:
df.groupby("Month")["Salary"].sum() # Aggregation based on group by

Month
1         0.0
2     20000.0
3     90000.0
10    18000.0
11    30000.0
12    25000.0
Name: Salary, dtype: float64

In [106]:
# different aggregation on different columns
df.groupby("Month").agg({"Salary": "mean", "Name" :'count'})

        Salary  Name
Month
1          NaN     1
2      20000.0     1
3      90000.0     1
10     18000.0     1
11     30000.0     1
12     25000.0     1

In [107]:
# concatenate and merge DataFrame(JOINS)

In [108]:
df1 = pd.DataFrame({"ID":[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [110]:
df2 = pd.DataFrame({'ID' :[1,2,3,4],'Score':[33,54,64,72]})
df2

   ID  Score
0   1     33
1   2     54
2   3     64
3   4     72

In [113]:
pd.concat([df1,df2],axis=0) # vertical / row level / top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   33.0
1   2  NaN   54.0
2   3  NaN   64.0
3   4  NaN   72.0

In [114]:
pd.concat([df1,df2],axis=1) # horizantal / row level / side on side

    ID Name  ID  Score
0  1.0    A   1     33
1  2.0    B   2     54
2  3.0    C   3     64
3  NaN  NaN   4     72

In [115]:
# merge = join
pd.merge(df1, df2, how="inner", on='ID')

   ID Name  Score
0   1    A     33
1   2    B     54
2   3    C     64

In [116]:
pd.merge(df1, df2, how='outer', on='ID')

   ID Name  Score
0   1    A     33
1   2    B     54
2   3    C     64
3   4  NaN     72

In [117]:
pd.merge(df1, df2, how='left', on='ID')

   ID Name  Score
0   1    A     33
1   2    B     54
2   3    C     64

In [118]:
pd.merge(df1, df2, how='outer', left_on='ID',right_on = 'ID')

   ID Name  Score
0   1    A     33
1   2    B     54
2   3    C     64
3   4  NaN     72